# Imports

In [168]:
import os
import json
import yaml
from pathlib import Path
import re
import datetime
from collections import defaultdict


import boto3
from dotenv import load_dotenv
import pandas as pd

# Environmental Variables

In [105]:
# set S3_BUCKET environmental variable to arn:aws:s3:::kasbench-test-20260528-377288663341-us-east-1-an
os.environ["S3_BUCKET"] = ""

In [18]:
load_dotenv()
s3_bucket = os.environ.get("S3_BUCKET")
print(f"S3 Bucket: {s3_bucket}")

S3 Bucket: kasbench-test-20260528-377288663341-us-east-1-an

# Constants

In [156]:
run_id = "verification-15-percentile-large-a"
s3 = boto3.client("s3")

data_directory = "../data"
output_directory = "../output"



monitored_events_text = """NodeNotReady
NodeUnreachable
NodeHasMemoryPressure
NodeHasDiskPressure
NodeHasPIDPressure
Evicted
OOMKilling
SystemOOM
FailedMount
FailedAttachVolume
FailedCreatePodSandBox
FailedPull
ErrImagePull
ImagePullBackOff
NetworkNotReady
FailedScheduling
Unhealthy
BackOff
CrashLoopBackOff
FailedCreate
FailedKillPod
FailedSync
Rebooted"""

monitored_events = [event for event in monitored_events_text.split("\n") if event]

# Functions

In [ ]:
def download_file_from_s3(s3_bucket, s3_key, local_path):
    """Download a file from S3 to a local path."""
    s3.download_file(s3_bucket, s3_key, local_path)
    print(f"Downloaded {s3_key} to {local_path}")


def get_s3_file_listing(s3_bucket, s3_prefix=''):
    """Get a listing of files in an S3 bucket."""
    file_list = []
    paginator = s3.get_paginator('list_objects_v2')
    pages = paginator.paginate(Bucket=s3_bucket, Prefix=s3_prefix)
    for page in pages:
        if 'Contents' in page:
            for obj in page['Contents']:
                file_list.append(obj)
    return file_list

def get_s3_file(s3_bucket, s3_filename, local_filename, data_directory, force=False):
    """Download a file from S3 to a local path."""

    # rename the local file
    local_filename = f"{data_directory}/{local_filename}"

    # skip if file exists and not force
    if os.path.exists(local_filename) and not force: 
        return local_filename
    
    
    # create the local directory, if it doesn't exist 

    dir_path = str(Path(f"{data_directory}/{local_filename}").parent)
    os.makedirs(dir_path, exist_ok=True)

    # download the tile
    s3.download_file(s3_bucket, s3_filename, local_filename)
    return local_filename

def parse_trial(filename):
    pattern = r"^[^/]+/(trial\d{4})/"
    if match := re.match(pattern, filename):
        return match.group(1)
    return None

In [152]:
def get_trial_start_end_times(files, run_id, s3_bucket, data_directory, force=False, verbose=False):
    trials = {}
    for file in files:
        if trial_id := parse_trial((file["Key"])):
            s3_filename = f"{run_id}/{trial_id}/run_details.json"
            local_filename = get_s3_file(s3_bucket, s3_filename, s3_filename, data_directory, force=force)
            with open(local_filename, "r") as f:
                trial = json.load(f)
                start_time = trial["status"]["startTime"] # string in format '2026-09-18T21:18:54.489000+00:00'
                end_time = trial["status"]["endTime"] # string in format '2026-09-18T21:18:54.489000+00:00'
                # convert start_time and end_time to timezone-aware dateteime objects
                start_time = datetime.datetime.fromisoformat(start_time.replace('Z', '+00:00'))
                end_time = datetime.datetime.fromisoformat(end_time.replace('Z', '+00:00'))
                trials[trial_id] = {"start_time": start_time, "end_time": end_time}

    if verbose:
        for trial_id, times in trials.items():
            print(f"{trial_id}: {times['start_time']} -> {times['end_time']}")

    return trials


def get_run_details(s3_bucket, run_id, trial_id, verbose=False):
    """Get the run details from S3"""
    key = f"{run_id}/{trial_id}/run_details.json"
    obj = s3.get_object(Bucket=s3_bucket, Key=key)
    return json.loads(obj['Body'].read())


def get_autoscaler(run_details):
    """ Get the autoscaler from the run details"""
    autoscaler = run_details["initialization"]["autoscaler"]
    return autoscaler

# Code

## Get the listing of files in the S3 bucket for the specified run

In [86]:
files = get_s3_file_listing(s3_bucket, run_id)

## Get the starting and ending time of each trial

In [89]:
trial_times = get_trial_start_end_times(files, run_id, s3_bucket, data_directory, force=False, verbose=False)        
trial_times

{'trial0001': {'start_time': datetime.datetime(2026, 9, 18, 20, 48, 48, 765649, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 18, 21, 18, 54, 489000, tzinfo=datetime.timezone.utc)},
 'trial0002': {'start_time': datetime.datetime(2026, 9, 18, 21, 40, 44, 31588, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 18, 22, 10, 49, 394000, tzinfo=datetime.timezone.utc)},
 'trial0003': {'start_time': datetime.datetime(2026, 9, 18, 22, 33, 0, 262451, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 18, 23, 3, 5, 59000, tzinfo=datetime.timezone.utc)},
 'trial0004': {'start_time': datetime.datetime(2026, 9, 18, 23, 24, 46, 327266, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 18, 23, 54, 50, 591000, tzinfo=datetime.timezone.utc)},
 'trial0005': {'start_time': datetime.datetime(2026, 9, 19, 0, 15, 53, 829765, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 0, 45, 59, 883000, tzinfo=datetime.timezone.utc)},
 'trial0006': {'start_time': datetime.datetime(2026, 9, 19, 1, 7, 41, 40769, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 1, 37, 46, 466000, tzinfo=datetime.timezone.utc)},
 'trial0007': {'start_time': datetime.datetime(2026, 9, 19, 1, 58, 10, 32732, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 2, 28, 14, 815000, tzinfo=datetime.timezone.utc)},
 'trial0008': {'start_time': datetime.datetime(2026, 9, 19, 2, 49, 38, 16823, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 3, 19, 42, 944000, tzinfo=datetime.timezone.utc)},
 'trial0009': {'start_time': datetime.datetime(2026, 9, 19, 3, 40, 39, 6191, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 4, 10, 43, 485000, tzinfo=datetime.timezone.utc)},
 'trial0010': {'start_time': datetime.datetime(2026, 9, 19, 4, 33, 27, 784625, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 5, 3, 32, 563000, tzinfo=datetime.timezone.utc)},
 'trial0011': {'start_time': datetime.datetime(2026, 9, 19, 5, 25, 22, 265083, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 5, 55, 28, 615000, tzinfo=datetime.timezone.utc)},
 'trial0012': {'start_time': datetime.datetime(2026, 9, 19, 6, 16, 42, 444584, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 6, 46, 47, 655000, tzinfo=datetime.timezone.utc)},
 'trial0013': {'start_time': datetime.datetime(2026, 9, 19, 7, 7, 19, 789721, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 7, 37, 25, 271000, tzinfo=datetime.timezone.utc)},
 'trial0014': {'start_time': datetime.datetime(2026, 9, 19, 7, 58, 29, 660102, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 8, 28, 34, 935000, tzinfo=datetime.timezone.utc)},
 'trial0015': {'start_time': datetime.datetime(2026, 9, 19, 8, 49, 44, 604894, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 9, 19, 49, 549000, tzinfo=datetime.timezone.utc)},
 'trial0016': {'start_time': datetime.datetime(2026, 9, 19, 9, 40, 37, 52369, tzinfo=datetime.timezone.utc),
  'end_time': datetime.datetime(2026, 9, 19, 10, 10, 42, 345000, tzinfo=datetime.timezone.utc)}}

## Analyze event logs (warnings.yaml)

In [158]:
results = []
reasons = set()
exclude_probes = False
counter = 0
autoscalers = {}
                
for file in files:
    if "post/events/warnings.yaml" in file["Key"]:
        filename = file["Key"]
        
        # parse the trial id from the filename
        trial_id = parse_trial(filename)

        # get the autoscaler
        autoscaler = autoscalers.get(trial_id)
        if autoscaler is None:
            run_details = get_run_details(s3_bucket, run_id, trial_id)
            autoscaler = get_autoscaler(run_details)
            autoscalers[trial_id] = autoscaler
            print(f"Trial: {trial_id} \tAutoscaler: {autoscaler}")
        
        # download the event file
        filename = get_s3_file(s3_bucket, filename, filename, data_directory)
        
        # load the event file
        with open(filename, "r") as f:
            events = yaml.load(f, Loader=yaml.FullLoader)
            
        for item in events["items"]:
            reason = item["reason"]
            type = item["type"]
            
            if  True:
                
                first_timestamp = item["firstTimestamp"] # string in format 2026-09-18T20:39:54Z
                last_timestamp = item["lastTimestamp"] # string in format 2026-09-18T20:39:54Z
                
                
                if first_timestamp is None or last_timestamp is None:
                    contineu

                # convert first_timestamp and last_timestamp to timezone aware datetimes
                first_timestamp = datetime.datetime.fromisoformat(first_timestamp.replace('Z', '+00:00'))
                last_timestamp = datetime.datetime.fromisoformat(last_timestamp.replace('Z', '+00:00'))
                
                # exclude events before and after the trial run
                if last_timestamp < trial_times[trial_id]["start_time"] or first_timestamp > trial_times[trial_id]["end_time"]:
                    continue

                reasons.add(reason)
            

                # gather relevant fields
                action = item.get("action")
                kind = item["involvedObject"]["kind"]
                name = item["involvedObject"]["name"]
                namespace = item["involvedObject"]["namespace"]
                message = item["message"]
                type = item["type"]
                count = item["count"]

                # exclude probe failures in the globeco namespace
                if exclude_probes and namespace == "globeco" and re.search("^(Readiness|Startup|Liveness) probe failed", message):
                    continue
                

                counter += 1
                print(f"*** {type}: {reason} ***")
                print(autoscaler)
                print(f"{first_timestamp} {last_timestamp}")
                print(f"{kind} {name} {namespace}")
                print(message)
                print(f"Count: {count}")
                print(f"Duration: {last_timestamp - first_timestamp}")
                # print(json.dumps(item, indent=2))
                print()

                results.append({
                    "action": action,
                    "type": type,
                    "reason": reason,
                    "count": count,
                    "first_timestamp": first_timestamp,
                    "last_timestamp": last_timestamp,
                    "trial_start_time": trial_times[trial_id]["start_time"],
                    "trial_end_time": trial_times[trial_id]["end_time"],
                    "duration": last_timestamp - first_timestamp,
                    "kind": kind,
                    "name": name,
                    "namespace": namespace,
                    "message": message,
                    "trial_id": trial_id,
                    "autoscaler": autoscaler,
                })
                
        # print(f"Trial: {trial_id} \tCounter: {counter}")    
        

print(reasons)    
print(results)
print(counter)

# write results array to a json file in the output directory
with open(f"{output_directory}/audit_results.json", "w") as f:
    json.dump(results, f, indent=2, default=str)

Trial: trial0001 	Autoscaler: hpa
*** Warning: Unhealthy ***
hpa
2026-09-18 20:47:38+00:00 2026-09-18 20:49:38+00:00
Pod globeco-fix-engine-d95677f59-9smgj globeco
Startup probe failed: Get "http://10.244.2.19:8085/healthz": dial tcp 10.244.2.19:8085: connect: connection refused
Count: 25
Duration: 0:02:00

*** Warning: FailedGetResourceMetric ***
hpa
2026-09-18 20:45:56+00:00 2026-09-18 20:50:41+00:00
HorizontalPodAutoscaler globeco-fix-engine-hpa globeco
failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
Count: 9
Duration: 0:04:45

*** Warning: Unhealthy ***
hpa
2026-09-18 21:02:27+00:00 2026-09-18 21:02:27+00:00
Pod globeco-order-generation-service-54cd6688b5-ndtd4 globeco
Readiness probe failed: Get "http://10.244.1.27:8088/health/ready": dial tcp 10.244.1.27:8088: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 20:50:52+00:00 2026-09-18 20:50:52+00:00
Pod globeco-order-service-6997c75c88-xh2ws globeco
Startup probe failed: Get "http://10.244.1.23:8081/actuator/health/readiness": dial tcp 10.244.1.23:8081: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 21:02:51+00:00 2026-09-18 21:02:51+00:00
Pod globeco-portfolio-service-8465f76dff-4fsxx globeco
Startup probe failed: Get "http://10.244.2.37:8000/": dial tcp 10.244.2.37:8000: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 21:03:47+00:00 2026-09-18 21:03:47+00:00
Pod globeco-portfolio-service-8465f76dff-7ck9n globeco
Startup probe failed: Get "http://10.244.1.28:8000/": dial tcp 10.244.1.28:8000: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: FailedGetResourceMetric ***
hpa
2026-09-18 20:48:11+00:00 2026-09-18 21:02:57+00:00
HorizontalPodAutoscaler globeco-portfolio-service-hpa globeco
failed to get cpu utilization: did not receive metrics for targeted pods (pods might be unready)
Count: 2
Duration: 0:14:46

*** Warning: FailedGetResourceMetric ***
hpa
2026-09-18 21:02:57+00:00 2026-09-18 21:02:57+00:00
HorizontalPodAutoscaler globeco-portfolio-service-hpa globeco
failed to get memory utilization: did not receive metrics for targeted pods (pods might be unready)
Count: 1
Duration: 0:00:00

*** Warning: FailedComputeMetricsReplicas ***
hpa
2026-09-18 21:02:57+00:00 2026-09-18 21:02:57+00:00
HorizontalPodAutoscaler globeco-portfolio-service-hpa globeco
invalid metrics (2 invalid out of 2), first error is: failed to get cpu resource metric value: failed to get cpu utilization: did not receive metrics for targeted pods (pods might be unready)
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 20:58:47+00:00 2026-09-18 20:58:47+00:00
Pod globeco-pricing-service-64498f4df5-99qn8 globeco
Startup probe failed: Get "http://10.244.1.26:8083/actuator/health/readiness": dial tcp 10.244.1.26:8083: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 20:52:57+00:00 2026-09-18 20:52:57+00:00
Pod globeco-pricing-service-64498f4df5-cm54h globeco
Startup probe failed: Get "http://10.244.2.35:8083/actuator/health/readiness": dial tcp 10.244.2.35:8083: connect: connection refused
Count: 1
Duration: 0:00:00

Trial: trial0002 	Autoscaler: hpa
*** Warning: Unhealthy ***
hpa
2026-09-18 21:54:12+00:00 2026-09-18 21:54:12+00:00
Pod globeco-order-generation-service-54cd6688b5-bkjrr globeco
Readiness probe failed: Get "http://10.244.2.35:8088/health/ready": dial tcp 10.244.2.35:8088: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 21:43:36+00:00 2026-09-18 21:43:36+00:00
Pod globeco-order-generation-service-54cd6688b5-zd6sk globeco
Startup probe failed: Get "http://10.244.1.27:8088/health/ready": dial tcp 10.244.1.27:8088: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
hpa
2026-09-18 21:43:21+00:00 2026-09-18 21:43:21+00:00
Pod globeco-order-service-6997c75c88-qtwqd globeco
Startup probe failed: Get "http://10.244.2.32:8081/actuator/health/readiness": dial tcp 10.244.2.32:8081: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: FailedGetResourceMetric ***
hpa
2026-09-18 21:38:41+00:00 2026-09-18 21:51:26+00:00
HorizontalPodAutoscaler globeco-portfolio-service-hpa globeco
failed to get cpu utilization: did not receive metrics for targeted pods (pods might be unready)
Count: 4
Duration: 0:12:45

*** Warning: FailedGetResourceMetric ***
hpa
2026-09-18 21:50:56+00:00 2026-09-18 21:51:11+00:00
HorizontalPodAutoscaler globeco-portfolio-service-hpa globeco
failed to get memory utilization: did not receive metrics for targeted pods (pods might be unready)
Count: 2
Duration: 0:00:15

*** Warning: FailedComputeMetricsReplicas ***
hpa
2026-09-18 21:50:56+00:00 2026-09-18 21:51:11+00:00
HorizontalPodAutoscaler globeco-portfolio-service-hpa globeco
invalid metrics (2 invalid out of 2), first error is: failed to get cpu resource metric value: failed to get cpu utilization: did not receive metrics for targeted pods (pods might be unready)
Count: 2
Duration: 0:00:15

*** Warning: Unhealthy ***
hpa
2026-09-18 21:42:36+00:00 2026-09-18 21:42:36+00:00
Pod globeco-security-service-799bb8cd5c-zjjwt globeco
Startup probe failed: Get "http://10.244.1.25:8000/health/startup": dial tcp 10.244.1.25:8000: connect: connection refused
Count: 1
Duration: 0:00:00

Trial: trial0003 	Autoscaler: vpa
*** Warning: Unhealthy ***
vpa
2026-09-18 22:33:49+00:00 2026-09-18 22:33:49+00:00
Pod globeco-allocation-service-857549f6d8-ccqp5 globeco
Readiness probe failed: Get "http://10.244.1.27:8089/readyz": dial tcp 10.244.1.27:8089: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
vpa
2026-09-18 22:33:49+00:00 2026-09-18 22:33:50+00:00
Pod globeco-fix-engine-d95677f59-jw5g6 globeco
Readiness probe failed: Get "http://10.244.1.12:8085/readyz": dial tcp 10.244.1.12:8085: connect: connection refused
Count: 2
Duration: 0:00:01

*** Warning: Unhealthy ***
vpa
2026-09-18 22:33:57+00:00 2026-09-18 22:33:57+00:00
Pod globeco-fix-engine-d95677f59-jw5g6 globeco
Startup probe failed: Get "http://10.244.1.12:8085/healthz": dial tcp 10.244.1.12:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
vpa
2026-09-18 22:34:49+00:00 2026-09-18 22:34:49+00:00
Pod globeco-portfolio-accounting-service-676786d77f-v892w globeco
Readiness probe failed: Get "http://10.244.1.26:8087/health/ready": dial tcp 10.244.1.26:8087: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
vpa
2026-09-18 22:33:49+00:00 2026-09-18 22:33:49+00:00
Pod globeco-portfolio-accounting-service-676786d77f-zhz76 globeco
Readiness probe failed: Get "http://10.244.2.22:8087/health/ready": dial tcp 10.244.2.22:8087: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
vpa
2026-09-18 22:48:10+00:00 2026-09-18 22:48:10+00:00
Pod globeco-portfolio-service-8465f76dff-wzp25 globeco
Startup probe failed: Get "http://10.244.2.38:8000/": dial tcp 10.244.2.38:8000: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
vpa
2026-09-18 22:31:52+00:00 2026-09-18 23:00:50+00:00
Pod globeco-trade-service-7fb64d5fb4-4kzwm globeco
Readiness probe failed: Get "http://10.244.2.11:8082/actuator/health/readiness": dial tcp 10.244.2.11:8082: connect: connection refused
Count: 6
Duration: 0:28:58

Trial: trial0004 	Autoscaler: keda
*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:41:30+00:00 2026-09-18 23:41:30+00:00
Pod globeco-confirmation-service-74dd5df469-27rg6 globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:39:45+00:00 2026-09-18 23:39:45+00:00
Pod globeco-confirmation-service-74dd5df469-69qpx globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:32:45+00:00 2026-09-18 23:32:45+00:00
Pod globeco-confirmation-service-74dd5df469-8rhmf globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:38:00+00:00 2026-09-18 23:38:00+00:00
Pod globeco-confirmation-service-74dd5df469-9xcsr globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:32:45+00:00 2026-09-18 23:32:45+00:00
Pod globeco-confirmation-service-74dd5df469-h7f6v globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:48:31+00:00 2026-09-18 23:48:31+00:00
Pod globeco-confirmation-service-74dd5df469-j5blb globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:48:31+00:00 2026-09-18 23:48:31+00:00
Pod globeco-confirmation-service-74dd5df469-j5blb globeco
Readiness probe failed: Get "http://10.244.2.68:8086/health/ready": dial tcp 10.244.2.68:8086: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:32:45+00:00 2026-09-18 23:32:45+00:00
Pod globeco-confirmation-service-74dd5df469-lkxfp globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:38:00+00:00 2026-09-18 23:38:00+00:00
Pod globeco-confirmation-service-74dd5df469-lqr2x globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:30:15+00:00 2026-09-18 23:30:15+00:00
Pod globeco-confirmation-service-74dd5df469-qzzsv globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:30:15+00:00 2026-09-18 23:30:15+00:00
Pod globeco-confirmation-service-74dd5df469-qzzsv globeco
Readiness probe failed: HTTP probe failed with statuscode: 503
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:48:16+00:00 2026-09-18 23:48:16+00:00
Pod globeco-confirmation-service-74dd5df469-xc8bp globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:29:15+00:00 2026-09-18 23:29:15+00:00
Pod globeco-confirmation-service-74dd5df469-xf6wn globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: FailedPreStopHook ***
keda
2026-09-18 23:34:15+00:00 2026-09-18 23:34:15+00:00
Pod globeco-confirmation-service-74dd5df469-z45t4 globeco
PreStopHook failed
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:36:27+00:00 2026-09-18 23:36:30+00:00
Pod globeco-execution-service-6df778fb86-smsdl globeco
Startup probe failed: Get "http://10.244.1.74:8084/actuator/health/readiness": dial tcp 10.244.1.74:8084: connect: connection refused
Count: 2
Duration: 0:00:03

*** Warning: Unhealthy ***
keda
2026-09-18 23:28:00+00:00 2026-09-18 23:28:00+00:00
Pod globeco-fix-engine-d95677f59-2fhk2 globeco
Readiness probe failed: Get "http://10.244.1.34:8085/readyz": dial tcp 10.244.1.34:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:29:45+00:00 2026-09-18 23:29:45+00:00
Pod globeco-fix-engine-d95677f59-2mqfk globeco
Readiness probe failed: Get "http://10.244.1.47:8085/readyz": dial tcp 10.244.1.47:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:51:46+00:00 2026-09-18 23:51:46+00:00
Pod globeco-fix-engine-d95677f59-2wxgw globeco
Startup probe failed: Get "http://10.244.2.104:8085/healthz": dial tcp 10.244.2.104:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:52:46+00:00 2026-09-18 23:52:46+00:00
Pod globeco-fix-engine-d95677f59-2wxgw globeco
Readiness probe failed: Get "http://10.244.2.104:8085/readyz": dial tcp 10.244.2.104:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:27:05+00:00 2026-09-18 23:27:05+00:00
Pod globeco-fix-engine-d95677f59-2zgxd globeco
Startup probe failed: Get "http://10.244.2.31:8085/healthz": dial tcp 10.244.2.31:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:28:00+00:00 2026-09-18 23:28:00+00:00
Pod globeco-fix-engine-d95677f59-2zgxd globeco
Readiness probe failed: Get "http://10.244.2.31:8085/readyz": dial tcp 10.244.2.31:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:35:00+00:00 2026-09-18 23:35:00+00:00
Pod globeco-fix-engine-d95677f59-42mjq globeco
Readiness probe failed: Get "http://10.244.1.64:8085/readyz": dial tcp 10.244.1.64:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:51:01+00:00 2026-09-18 23:51:01+00:00
Pod globeco-fix-engine-d95677f59-49bzm globeco
Readiness probe failed: Get "http://10.244.2.99:8085/readyz": dial tcp 10.244.2.99:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:54:31+00:00 2026-09-18 23:54:31+00:00
Pod globeco-fix-engine-d95677f59-4cwsl globeco
Readiness probe failed: Get "http://10.244.2.112:8085/readyz": dial tcp 10.244.2.112:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:44:16+00:00 2026-09-18 23:44:16+00:00
Pod globeco-fix-engine-d95677f59-4gqm8 globeco
Readiness probe failed: Get "http://10.244.2.76:8085/readyz": dial tcp 10.244.2.76:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:28:45+00:00 2026-09-18 23:28:45+00:00
Pod globeco-fix-engine-d95677f59-4rhv2 globeco
Startup probe failed: Get "http://10.244.2.43:8085/healthz": dial tcp 10.244.2.43:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:29:45+00:00 2026-09-18 23:29:45+00:00
Pod globeco-fix-engine-d95677f59-4rhv2 globeco
Readiness probe failed: Get "http://10.244.2.43:8085/readyz": dial tcp 10.244.2.43:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:35:00+00:00 2026-09-18 23:35:00+00:00
Pod globeco-fix-engine-d95677f59-4xnk9 globeco
Readiness probe failed: Get "http://10.244.1.61:8085/readyz": dial tcp 10.244.1.61:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:41:01+00:00 2026-09-18 23:41:01+00:00
Pod globeco-fix-engine-d95677f59-579dc globeco
Startup probe failed: Get "http://10.244.1.87:8085/healthz": dial tcp 10.244.1.87:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:42:16+00:00 2026-09-18 23:42:16+00:00
Pod globeco-fix-engine-d95677f59-579dc globeco
Readiness probe failed: Get "http://10.244.1.87:8085/readyz": dial tcp 10.244.1.87:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:35:00+00:00 2026-09-18 23:35:00+00:00
Pod globeco-fix-engine-d95677f59-57wc7 globeco
Readiness probe failed: Get "http://10.244.2.54:8085/readyz": dial tcp 10.244.2.54:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:31:30+00:00 2026-09-18 23:31:30+00:00
Pod globeco-fix-engine-d95677f59-5qm7k globeco
Readiness probe failed: Get "http://10.244.2.47:8085/readyz": dial tcp 10.244.2.47:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:43:01+00:00 2026-09-18 23:43:01+00:00
Pod globeco-fix-engine-d95677f59-5qzxx globeco
Startup probe failed: Get "http://10.244.2.78:8085/healthz": dial tcp 10.244.2.78:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:44:01+00:00 2026-09-18 23:44:01+00:00
Pod globeco-fix-engine-d95677f59-5qzxx globeco
Readiness probe failed: Get "http://10.244.2.78:8085/readyz": dial tcp 10.244.2.78:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:54:31+00:00 2026-09-18 23:54:31+00:00
Pod globeco-fix-engine-d95677f59-67fdv globeco
Readiness probe failed: Get "http://10.244.1.108:8085/readyz": dial tcp 10.244.1.108:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:39:00+00:00 2026-09-18 23:39:00+00:00
Pod globeco-fix-engine-d95677f59-6b2l6 globeco
Startup probe failed: Get "http://10.244.1.81:8085/healthz": dial tcp 10.244.1.81:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:40:30+00:00 2026-09-18 23:40:30+00:00
Pod globeco-fix-engine-d95677f59-6b2l6 globeco
Readiness probe failed: Get "http://10.244.1.81:8085/readyz": dial tcp 10.244.1.81:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:36:45+00:00 2026-09-18 23:36:45+00:00
Pod globeco-fix-engine-d95677f59-6t94b globeco
Readiness probe failed: Get "http://10.244.2.60:8085/readyz": dial tcp 10.244.2.60:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:33:45+00:00 2026-09-18 23:33:45+00:00
Pod globeco-fix-engine-d95677f59-6v264 globeco
Startup probe failed: Get "http://10.244.2.53:8085/healthz": dial tcp 10.244.2.53:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:35:00+00:00 2026-09-18 23:35:00+00:00
Pod globeco-fix-engine-d95677f59-6v264 globeco
Readiness probe failed: Get "http://10.244.2.53:8085/readyz": dial tcp 10.244.2.53:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:33:15+00:00 2026-09-18 23:33:15+00:00
Pod globeco-fix-engine-d95677f59-6vv56 globeco
Readiness probe failed: Get "http://10.244.1.58:8085/readyz": dial tcp 10.244.1.58:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:28:00+00:00 2026-09-18 23:28:00+00:00
Pod globeco-fix-engine-d95677f59-77zn7 globeco
Readiness probe failed: Get "http://10.244.1.33:8085/readyz": dial tcp 10.244.1.33:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:26:45+00:00 2026-09-18 23:26:45+00:00
Pod globeco-fix-engine-d95677f59-7hh6m globeco
Startup probe failed: Get "http://10.244.1.32:8085/healthz": dial tcp 10.244.1.32:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:28:00+00:00 2026-09-18 23:28:00+00:00
Pod globeco-fix-engine-d95677f59-7hh6m globeco
Readiness probe failed: Get "http://10.244.1.32:8085/readyz": dial tcp 10.244.1.32:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:45:01+00:00 2026-09-18 23:45:01+00:00
Pod globeco-fix-engine-d95677f59-7nlbr globeco
Startup probe failed: Get "http://10.244.2.82:8085/healthz": dial tcp 10.244.2.82:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:46:06+00:00 2026-09-18 23:46:06+00:00
Pod globeco-fix-engine-d95677f59-7nlbr globeco
Readiness probe failed: Get "http://10.244.2.82:8085/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:43:01+00:00 2026-09-18 23:43:01+00:00
Pod globeco-fix-engine-d95677f59-7pbrw globeco
Startup probe failed: Get "http://10.244.1.93:8085/healthz": dial tcp 10.244.1.93:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:44:01+00:00 2026-09-18 23:44:01+00:00
Pod globeco-fix-engine-d95677f59-7pbrw globeco
Readiness probe failed: Get "http://10.244.1.93:8085/readyz": dial tcp 10.244.1.93:8085: connect: connection refused
Count: 1
Duration: 0:00:00

*** Warning: Unhealthy ***
keda
2026-09-18 23:31:30+00:00 2026-09-18 23:31:30+00:00
Pod globeco-fix-engine-d95677f59-8wnnx globeco

In [103]:
results

[]

In [163]:
count = 0
for result in results:
    if result["reason"] == "FailedGetResourceMetric" and result["name"] != "globeco-portfolio-service-hpa":
        print(result["name"], result["trial_id"], result["count"], result["autoscaler"])
        count += 1
print(count)

globeco-fix-engine-hpa trial0001 9 hpa
globeco-order-generation-service-hpa trial0004 1 keda
globeco-order-service-hpa trial0004 8 keda
globeco-portfolio-accounting-service-hpa trial0004 8 keda
globeco-security-service-hpa trial0004 1 keda
globeco-fix-engine-hpa trial0008 13 hpa
globeco-execution-service-hpa trial0013 1 keda
globeco-order-generation-service-hpa trial0013 8 keda
globeco-order-service-hpa trial0013 1 keda
globeco-portfolio-accounting-service-hpa trial0013 8 keda
globeco-fix-engine-hpa trial0014 9 hpa
globeco-allocation-service-hpa trial0015 1 keda
globeco-trade-service-hpa trial0015 1 keda
13

In [166]:
autoscalers = ["keda", "hpa"]
for autoscaler in autoscalers:
    count = 0
    for result in results:
        if result["autoscaler"] == autoscaler:
            print(result["name"], result["trial_id"], result["count"], result["autoscaler"])
            count += 1
    print(f"{autoscaler}: {count}")

globeco-confirmation-service-74dd5df469-27rg6 trial0004 1 keda
globeco-confirmation-service-74dd5df469-69qpx trial0004 1 keda
globeco-confirmation-service-74dd5df469-8rhmf trial0004 1 keda
globeco-confirmation-service-74dd5df469-9xcsr trial0004 1 keda
globeco-confirmation-service-74dd5df469-h7f6v trial0004 1 keda
globeco-confirmation-service-74dd5df469-j5blb trial0004 1 keda
globeco-confirmation-service-74dd5df469-j5blb trial0004 1 keda
globeco-confirmation-service-74dd5df469-lkxfp trial0004 1 keda
globeco-confirmation-service-74dd5df469-lqr2x trial0004 1 keda
globeco-confirmation-service-74dd5df469-qzzsv trial0004 1 keda
globeco-confirmation-service-74dd5df469-qzzsv trial0004 1 keda
globeco-confirmation-service-74dd5df469-xc8bp trial0004 1 keda
globeco-confirmation-service-74dd5df469-xf6wn trial0004 1 keda
globeco-confirmation-service-74dd5df469-z45t4 trial0004 1 keda
globeco-execution-service-6df778fb86-smsdl trial0004 2 keda
globeco-fix-engine-d95677f59-2fhk2 trial0004 1 keda
globeco-fix-engine-d95677f59-2mqfk trial0004 1 keda
globeco-fix-engine-d95677f59-2wxgw trial0004 1 keda
globeco-fix-engine-d95677f59-2wxgw trial0004 1 keda
globeco-fix-engine-d95677f59-2zgxd trial0004 1 keda
globeco-fix-engine-d95677f59-2zgxd trial0004 1 keda
globeco-fix-engine-d95677f59-42mjq trial0004 1 keda
globeco-fix-engine-d95677f59-49bzm trial0004 1 keda
globeco-fix-engine-d95677f59-4cwsl trial0004 1 keda
globeco-fix-engine-d95677f59-4gqm8 trial0004 1 keda
globeco-fix-engine-d95677f59-4rhv2 trial0004 1 keda
globeco-fix-engine-d95677f59-4rhv2 trial0004 1 keda
globeco-fix-engine-d95677f59-4xnk9 trial0004 1 keda
globeco-fix-engine-d95677f59-579dc trial0004 1 keda
globeco-fix-engine-d95677f59-579dc trial0004 1 keda
globeco-fix-engine-d95677f59-57wc7 trial0004 1 keda
globeco-fix-engine-d95677f59-5qm7k trial0004 1 keda
globeco-fix-engine-d95677f59-5qzxx trial0004 1 keda
globeco-fix-engine-d95677f59-5qzxx trial0004 1 keda
globeco-fix-engine-d95677f59-67fdv trial0004 1 keda
globeco-fix-engine-d95677f59-6b2l6 trial0004 1 keda
globeco-fix-engine-d95677f59-6b2l6 trial0004 1 keda
globeco-fix-engine-d95677f59-6t94b trial0004 1 keda
globeco-fix-engine-d95677f59-6v264 trial0004 1 keda
globeco-fix-engine-d95677f59-6v264 trial0004 1 keda
globeco-fix-engine-d95677f59-6vv56 trial0004 1 keda
globeco-fix-engine-d95677f59-77zn7 trial0004 1 keda
globeco-fix-engine-d95677f59-7hh6m trial0004 1 keda
globeco-fix-engine-d95677f59-7hh6m trial0004 1 keda
globeco-fix-engine-d95677f59-7nlbr trial0004 1 keda
globeco-fix-engine-d95677f59-7nlbr trial0004 1 keda
globeco-fix-engine-d95677f59-7pbrw trial0004 1 keda
globeco-fix-engine-d95677f59-7pbrw trial0004 1 keda
globeco-fix-engine-d95677f59-8wnnx trial0004 1 keda
globeco-fix-engine-d95677f59-95lvg trial0004 1 keda
globeco-fix-engine-d95677f59-95lvg trial0004 1 keda
globeco-fix-engine-d95677f59-9ctsd trial0004 1 keda
globeco-fix-engine-d95677f59-9pr6n trial0004 1 keda
globeco-fix-engine-d95677f59-9pr6n trial0004 1 keda
globeco-fix-engine-d95677f59-9qctv trial0004 1 keda
globeco-fix-engine-d95677f59-9t8jh trial0004 1 keda
globeco-fix-engine-d95677f59-9t8jh trial0004 1 keda
globeco-fix-engine-d95677f59-9vqvx trial0004 1 keda
globeco-fix-engine-d95677f59-9vqvx trial0004 1 keda
globeco-fix-engine-d95677f59-b4cbm trial0004 1 keda
globeco-fix-engine-d95677f59-b4f5s trial0004 1 keda
globeco-fix-engine-d95677f59-b4tgv trial0004 1 keda
globeco-fix-engine-d95677f59-bsz5z trial0004 1 keda
globeco-fix-engine-d95677f59-bwdv5 trial0004 1 keda
globeco-fix-engine-d95677f59-ch75k trial0004 1 keda
globeco-fix-engine-d95677f59-ch75k trial0004 1 keda
globeco-fix-engine-d95677f59-crhpj trial0004 1 keda
globeco-fix-engine-d95677f59-crhpj trial0004 1 keda
globeco-fix-engine-d95677f59-cvgzn trial0004 1 keda
globeco-fix-engine-d95677f59-dwmtd trial0004 1 keda
globeco-fix-engine-d95677f59-dwmtd trial0004 1 keda
globeco-fix-engine-d95677f59-dzwqz trial0004 1 keda
globeco-fix-engine-d95677f59-fh6h9 trial0004 1 keda
globeco-fix-engine-d95677f59-fh6h9 trial0004 1 keda
globeco-fix-engine-d95677f59-fhhdm trial0004 1 keda
globeco-fix-engine-d95677f59-fkcj8 trial0004 1 keda
globeco-fix-engine-d95677f59-fqk4n trial0004 1 keda
globeco-fix-engine-d95677f59-fqk4n trial0004 1 keda
globeco-fix-engine-d95677f59-ftm7l trial0004 1 keda
globeco-fix-engine-d95677f59-fvtjb trial0004 1 keda
globeco-fix-engine-d95677f59-g8tzh trial0004 1 keda
globeco-fix-engine-d95677f59-gbrnh trial0004 1 keda
globeco-fix-engine-d95677f59-gl7qv trial0004 1 keda
globeco-fix-engine-d95677f59-gl7qv trial0004 1 keda
globeco-fix-engine-d95677f59-grzsk trial0004 1 keda
globeco-fix-engine-d95677f59-grzsk trial0004 1 keda
globeco-fix-engine-d95677f59-gs78s trial0004 1 keda
globeco-fix-engine-d95677f59-h4gs2 trial0004 1 keda
globeco-fix-engine-d95677f59-hcn2m trial0004 1 keda
globeco-fix-engine-d95677f59-hcn2m trial0004 1 keda
globeco-fix-engine-d95677f59-hd9px trial0004 1 keda
globeco-fix-engine-d95677f59-hd9px trial0004 1 keda
globeco-fix-engine-d95677f59-hjcnm trial0004 1 keda
globeco-fix-engine-d95677f59-hjcnm trial0004 1 keda
globeco-fix-engine-d95677f59-hnv26 trial0004 1 keda
globeco-fix-engine-d95677f59-hnv26 trial0004 1 keda
globeco-fix-engine-d95677f59-hvw5l trial0004 1 keda
globeco-fix-engine-d95677f59-hvw5l trial0004 1 keda
globeco-fix-engine-d95677f59-hx87q trial0004 1 keda
globeco-fix-engine-d95677f59-j6jx9 trial0004 1 keda
globeco-fix-engine-d95677f59-jsfvc trial0004 1 keda
globeco-fix-engine-d95677f59-jxk48 trial0004 1 keda
globeco-fix-engine-d95677f59-jxk48 trial0004 1 keda
globeco-fix-engine-d95677f59-kb4z6 trial0004 1 keda
globeco-fix-engine-d95677f59-kqz82 trial0004 1 keda
globeco-fix-engine-d95677f59-kvmgf trial0004 1 keda
globeco-fix-engine-d95677f59-kvmgf trial0004 1 keda
globeco-fix-engine-d95677f59-l6q4l trial0004 1 keda
globeco-fix-engine-d95677f59-l6q4l trial0004 1 keda
globeco-fix-engine-d95677f59-lfbpr trial0004 1 keda
globeco-fix-engine-d95677f59-ltlxg trial0004 1 keda
globeco-fix-engine-d95677f59-m24rm trial0004 1 keda
globeco-fix-engine-d95677f59-m4sbc trial0004 1 keda
globeco-fix-engine-d95677f59-m4sbc trial0004 1 keda
globeco-fix-engine-d95677f59-m9479 trial0004 1 keda
globeco-fix-engine-d95677f59-mkf4s trial0004 1 keda
globeco-fix-engine-d95677f59-mx69w trial0004 1 keda
globeco-fix-engine-d95677f59-n9xzk trial0004 1 keda
globeco-fix-engine-d95677f59-n9xzk trial0004 1 keda
globeco-fix-engine-d95677f59-ngsqd trial0004 1 keda
globeco-fix-engine-d95677f59-ngsqd trial0004 1 keda
globeco-fix-engine-d95677f59-nm5lb trial0004 1 keda
globeco-fix-engine-d95677f59-nm5lb trial0004 1 keda
globeco-fix-engine-d95677f59-ntbf4 trial0004 1 keda
globeco-fix-engine-d95677f59-p7gn8 trial0004 1 keda
globeco-fix-engine-d95677f59-phf8t trial0004 1 keda
globeco-fix-engine-d95677f59-phf8t trial0004 1 keda
globeco-fix-engine-d95677f59-pjc4w trial0004 1 keda
globeco-fix-engine-d95677f59-q9dsc trial0004 1 keda
globeco-fix-engine-d95677f59-q9dsc trial0004 1 keda
globeco-fix-engine-d95677f59-q9pgr trial0004 1 keda
globeco-fix-engine-d95677f59-qfbs2 trial0004 1 keda
globeco-fix-engine-d95677f59-qgd6t trial0004 1 keda
globeco-fix-engine-d95677f59-qgd6t trial0004 1 keda
globeco-fix-engine-d95677f59-qh8qs trial0004 1 keda
globeco-fix-engine-d95677f59-qmtgn trial0004 1 keda
globeco-fix-engine-d95677f59-qmtgn trial0004 1 keda
globeco-fix-engine-d95677f59-qqssk trial0004 1 keda
globeco-fix-engine-d95677f59-r4srh trial0004 1 keda
globeco-fix-engine-d95677f59-rs2qg trial0004 1 keda
globeco-fix-engine-d95677f59-s7lrf trial0004 1 keda
globeco-fix-engine-d95677f59-sk84w trial0004 1 keda
globeco-fix-engine-d95677f59-spp9w trial0004 1 keda
globeco-fix-engine-d95677f59-t9275 trial0004 1 keda
globeco-fix-engine-d95677f59-tndgn trial0004 1 keda
globeco-fix-engine-d95677f59-tndgn trial0004 1 keda
globeco-fix-engine-d95677f59-tthnv trial0004 1 keda
globeco-fix-engine-d95677f59-ttxlq trial0004 1 keda
globeco-fix-engine-d95677f59-tvz9c trial0004 1 keda
globeco-fix-engine-d95677f59-v6lq9 trial0004 1 keda
globeco-fix-engine-d95677f59-v7bzf trial0004 1 keda
globeco-fix-engine-d95677f59-v7bzf trial0004 1 keda
globeco-fix-engine-d95677f59-vpcwh trial0004 1 keda
globeco-fix-engine-d95677f59-w2jbc trial0004 1 keda
globeco-fix-engine-d95677f59-w8mf7 trial0004 1 keda
globeco-fix-engine-d95677f59-wcvfc trial0004 1 keda
globeco-fix-engine-d95677f59-wg88k trial0004 1 keda
globeco-fix-engine-d95677f59-wg88k trial0004 1 keda
globeco-fix-engine-d95677f59-wgjz4 trial0004 1 keda
globeco-fix-engine-d95677f59-xqhtx trial0004 1 keda
globeco-fix-engine-d95677f59-xqhtx trial0004 1 keda
globeco-fix-engine-d95677f59-xz26n trial0004 1 keda
globeco-fix-engine-d95677f59-xz26n trial0004 1 keda
globeco-fix-engine-d95677f59-z6625 trial0004 1 keda
globeco-fix-engine-d95677f59-z7mtg trial0004 1 keda
globeco-fix-engine-d95677f59-z7mtg trial0004 1 keda
globeco-fix-engine-d95677f59-z82s6 trial0004 1 keda
globeco-fix-engine-d95677f59-zc8vt trial0004 1 keda
globeco-fix-engine-d95677f59-zjmjb trial0004 1 keda
globeco-order-generation-service-54cd6688b5-cmrtf trial0004 1 keda
globeco-order-generation-service-54cd6688b5-pjfmc trial0004 1 keda
globeco-order-generation-service-54cd6688b5-r2hq8 trial0004 1 keda
globeco-order-generation-service-hpa trial0004 1 keda
globeco-order-service-6997c75c88-rnlwl trial0004 1 keda
globeco-order-service-hpa trial0004 8 keda
globeco-portfolio-accounting-service-hpa trial0004 8 keda
globeco-portfolio-service-8465f76dff-frsm8 trial0004 1 keda
globeco-portfolio-service-8465f76dff-npscc trial0004 1 keda
globeco-portfolio-service-hpa trial0004 4 keda
globeco-portfolio-service-hpa trial0004 1 keda
globeco-portfolio-service-hpa trial0004 1 keda
globeco-pricing-service-64498f4df5-9hjb6 trial0004 1 keda
globeco-pricing-service-64498f4df5-jslvr trial0004 1 keda
globeco-pricing-service-64498f4df5-lckpj trial0004 1 keda
globeco-pricing-service-64498f4df5-tmpgs trial0004 1 keda
globeco-security-service-799bb8cd5c-lq6mk trial0004 1 keda
globeco-security-service-799bb8cd5c-lq6mk trial0004 1 keda
globeco-security-service-hpa trial0004 1 keda
globeco-trade-service-7fb64d5fb4-xkc9c trial0004 1 keda
globeco-confirmation-service-74dd5df469-fw88h trial0009 1 keda
globeco-confirmation-service-74dd5df469-g6242 trial0009 1 keda
globeco-confirmation-service-74dd5df469-gdndk trial0009 1 keda
globeco-confirmation-service-74dd5df469-gjf9g trial0009 1 keda
globeco-confirmation-service-74dd5df469-kmvfm trial0009 1 keda
globeco-confirmation-service-74dd5df469-mr52t trial0009 1 keda
globeco-confirmation-service-74dd5df469-vd4tt trial0009 1 keda
globeco-confirmation-service-74dd5df469-vwbjs trial0009 1 keda
globeco-confirmation-service-74dd5df469-w877z trial0009 1 keda
globeco-execution-service-6df778fb86-qkfnh trial0009 1 keda
globeco-fix-engine-d95677f59-2f9gf trial0009 1 keda
globeco-fix-engine-d95677f59-2nhn6 trial0009 1 keda
globeco-fix-engine-d95677f59-2tvjb trial0009 1 keda
globeco-fix-engine-d95677f59-4jg8g trial0009 1 keda
globeco-fix-engine-d95677f59-4n4lj trial0009 1 keda
globeco-fix-engine-d95677f59-4n4lj trial0009 1 keda
globeco-fix-engine-d95677f59-4n5cf trial0009 1 keda
globeco-fix-engine-d95677f59-4r296 trial0009 1 keda
globeco-fix-engine-d95677f59-52gz4 trial0009 1 keda
globeco-fix-engine-d95677f59-52gz4 trial0009 1 keda
globeco-fix-engine-d95677f59-5cbtk trial0009 1 keda
globeco-fix-engine-d95677f59-5cjrt trial0009 1 keda
globeco-fix-engine-d95677f59-5fmj7 trial0009 1 keda
globeco-fix-engine-d95677f59-5hdlg trial0009 1 keda
globeco-fix-engine-d95677f59-5m49q trial0009 1 keda
globeco-fix-engine-d95677f59-5mfbt trial0009 1 keda
globeco-fix-engine-d95677f59-5pqxw trial0009 1 keda
globeco-fix-engine-d95677f59-5w4rv trial0009 1 keda
globeco-fix-engine-d95677f59-66h4h trial0009 2 keda
globeco-fix-engine-d95677f59-66h4h trial0009 1 keda
globeco-fix-engine-d95677f59-6fzx8 trial0009 1 keda
globeco-fix-engine-d95677f59-6p22n trial0009 1 keda
globeco-fix-engine-d95677f59-6qn6x trial0009 1 keda
globeco-fix-engine-d95677f59-6x8sp trial0009 1 keda
globeco-fix-engine-d95677f59-74zws trial0009 1 keda
globeco-fix-engine-d95677f59-7q7b9 trial0009 1 keda
globeco-fix-engine-d95677f59-7v52f trial0009 1 keda
globeco-fix-engine-d95677f59-7v52f trial0009 1 keda
globeco-fix-engine-d95677f59-7w5fj trial0009 1 keda
globeco-fix-engine-d95677f59-7w5fj trial0009 1 keda
globeco-fix-engine-d95677f59-87mcg trial0009 1 keda
globeco-fix-engine-d95677f59-8fdp6 trial0009 1 keda
globeco-fix-engine-d95677f59-8fdp6 trial0009 1 keda
globeco-fix-engine-d95677f59-8frc9 trial0009 1 keda
globeco-fix-engine-d95677f59-8hxth trial0009 1 keda
globeco-fix-engine-d95677f59-8ljm2 trial0009 1 keda
globeco-fix-engine-d95677f59-8ljm2 trial0009 1 keda
globeco-fix-engine-d95677f59-8ltpl trial0009 1 keda
globeco-fix-engine-d95677f59-8ltpl trial0009 1 keda
globeco-fix-engine-d95677f59-8nvhg trial0009 2 keda
globeco-fix-engine-d95677f59-8nvhg trial0009 1 keda
globeco-fix-engine-d95677f59-8pl2t trial0009 1 keda
globeco-fix-engine-d95677f59-8vgqc trial0009 1 keda
globeco-fix-engine-d95677f59-8zz26 trial0009 1 keda
globeco-fix-engine-d95677f59-8zz26 trial0009 1 keda
globeco-fix-engine-d95677f59-97hvn trial0009 1 keda
globeco-fix-engine-d95677f59-97hvn trial0009 1 keda
globeco-fix-engine-d95677f59-99c9x trial0009 1 keda
globeco-fix-engine-d95677f59-9khzg trial0009 1 keda
globeco-fix-engine-d95677f59-9m94n trial0009 1 keda
globeco-fix-engine-d95677f59-9nd6s trial0009 1 keda
globeco-fix-engine-d95677f59-9rnzd trial0009 1 keda
globeco-fix-engine-d95677f59-b2m9j trial0009 1 keda
globeco-fix-engine-d95677f59-b2m9j trial0009 1 keda
globeco-fix-engine-d95677f59-bhcrs trial0009 1 keda
globeco-fix-engine-d95677f59-bjnhg trial0009 1 keda
globeco-fix-engine-d95677f59-btbj2 trial0009 1 keda
globeco-fix-engine-d95677f59-btbj2 trial0009 1 keda
globeco-fix-engine-d95677f59-cngp9 trial0009 1 keda
globeco-fix-engine-d95677f59-cngp9 trial0009 1 keda
globeco-fix-engine-d95677f59-cwgsp trial0009 1 keda
globeco-fix-engine-d95677f59-cwgsp trial0009 1 keda
globeco-fix-engine-d95677f59-dc5xq trial0009 1 keda
globeco-fix-engine-d95677f59-dc5xq trial0009 1 keda
globeco-fix-engine-d95677f59-df7rk trial0009 1 keda
globeco-fix-engine-d95677f59-df7rk trial0009 1 keda
globeco-fix-engine-d95677f59-dj5tc trial0009 1 keda
globeco-fix-engine-d95677f59-dj5tc trial0009 1 keda
globeco-fix-engine-d95677f59-djlhx trial0009 1 keda
globeco-fix-engine-d95677f59-dlm7h trial0009 1 keda
globeco-fix-engine-d95677f59-fczbh trial0009 1 keda
globeco-fix-engine-d95677f59-g2fhq trial0009 1 keda
globeco-fix-engine-d95677f59-gddwf trial0009 1 keda
globeco-fix-engine-d95677f59-grncv trial0009 1 keda
globeco-fix-engine-d95677f59-grnhw trial0009 1 keda
globeco-fix-engine-d95677f59-hhtzd trial0009 1 keda
globeco-fix-engine-d95677f59-hkfk6 trial0009 1 keda
globeco-fix-engine-d95677f59-hwz47 trial0009 1 keda
globeco-fix-engine-d95677f59-hxdl9 trial0009 1 keda
globeco-fix-engine-d95677f59-hxdl9 trial0009 1 keda
globeco-fix-engine-d95677f59-jl475 trial0009 1 keda
globeco-fix-engine-d95677f59-jr2fh trial0009 1 keda
globeco-fix-engine-d95677f59-kd5jv trial0009 1 keda
globeco-fix-engine-d95677f59-kd5jv trial0009 1 keda
globeco-fix-engine-d95677f59-kjht7 trial0009 1 keda
globeco-fix-engine-d95677f59-klt75 trial0009 1 keda
globeco-fix-engine-d95677f59-l5xkj trial0009 1 keda
globeco-fix-engine-d95677f59-l6m24 trial0009 1 keda
globeco-fix-engine-d95677f59-l6m24 trial0009 1 keda
globeco-fix-engine-d95677f59-lhfxb trial0009 1 keda
globeco-fix-engine-d95677f59-lhfxb trial0009 1 keda
globeco-fix-engine-d95677f59-ml9gl trial0009 1 keda
globeco-fix-engine-d95677f59-ml9gl trial0009 1 keda
globeco-fix-engine-d95677f59-mlgvp trial0009 1 keda
globeco-fix-engine-d95677f59-mlnsr trial0009 1 keda
globeco-fix-engine-d95677f59-mwtcd trial0009 1 keda
globeco-fix-engine-d95677f59-n2lbx trial0009 1 keda
globeco-fix-engine-d95677f59-n56xc trial0009 1 keda
globeco-fix-engine-d95677f59-n9z5h trial0009 1 keda
globeco-fix-engine-d95677f59-nfzn8 trial0009 1 keda
globeco-fix-engine-d95677f59-nlw2f trial0009 1 keda
globeco-fix-engine-d95677f59-nlw2f trial0009 1 keda
globeco-fix-engine-d95677f59-nrjhd trial0009 1 keda
globeco-fix-engine-d95677f59-nrjhd trial0009 1 keda
globeco-fix-engine-d95677f59-prmwf trial0009 1 keda
globeco-fix-engine-d95677f59-prmwf trial0009 1 keda
globeco-fix-engine-d95677f59-psns5 trial0009 1 keda
globeco-fix-engine-d95677f59-psns5 trial0009 1 keda
globeco-fix-engine-d95677f59-q4s95 trial0009 1 keda
globeco-fix-engine-d95677f59-q8x44 trial0009 1 keda
globeco-fix-engine-d95677f59-qj58s trial0009 1 keda
globeco-fix-engine-d95677f59-qlqj9 trial0009 1 keda
globeco-fix-engine-d95677f59-qp5rl trial0009 1 keda
globeco-fix-engine-d95677f59-qwrtr trial0009 1 keda
globeco-fix-engine-d95677f59-qxf9v trial0009 1 keda
globeco-fix-engine-d95677f59-qxf9v trial0009 1 keda
globeco-fix-engine-d95677f59-r7z7s trial0009 1 keda
globeco-fix-engine-d95677f59-s8jrc trial0009 1 keda
globeco-fix-engine-d95677f59-shk5p trial0009 1 keda
globeco-fix-engine-d95677f59-sv6hj trial0009 1 keda
globeco-fix-engine-d95677f59-sv8gs trial0009 1 keda
globeco-fix-engine-d95677f59-sw9t6 trial0009 1 keda
globeco-fix-engine-d95677f59-t5c2k trial0009 1 keda
globeco-fix-engine-d95677f59-t745j trial0009 1 keda
globeco-fix-engine-d95677f59-t745j trial0009 1 keda
globeco-fix-engine-d95677f59-v2j2k trial0009 1 keda
globeco-fix-engine-d95677f59-vnn9n trial0009 1 keda
globeco-fix-engine-d95677f59-vspbx trial0009 1 keda
globeco-fix-engine-d95677f59-vspbx trial0009 1 keda
globeco-fix-engine-d95677f59-w99lc trial0009 1 keda
globeco-fix-engine-d95677f59-w99lc trial0009 1 keda
globeco-fix-engine-d95677f59-wq9wb trial0009 1 keda
globeco-fix-engine-d95677f59-wrw7f trial0009 1 keda
globeco-fix-engine-d95677f59-wrw7f trial0009 1 keda
globeco-fix-engine-d95677f59-wxjpc trial0009 1 keda
globeco-fix-engine-d95677f59-wxjpc trial0009 1 keda
globeco-fix-engine-d95677f59-xmv5f trial0009 1 keda
globeco-fix-engine-d95677f59-xmxp8 trial0009 1 keda
globeco-fix-engine-d95677f59-xmxp8 trial0009 1 keda
globeco-fix-engine-d95677f59-xt5md trial0009 1 keda
globeco-fix-engine-d95677f59-zqfv4 trial0009 1 keda
globeco-fix-engine-d95677f59-ztlhw trial0009 1 keda
globeco-fix-engine-d95677f59-zwjsm trial0009 1 keda
globeco-order-generation-service-54cd6688b5-6xs4b trial0009 1 keda
globeco-order-generation-service-54cd6688b5-mb6vn trial0009 1 keda
globeco-order-service-6997c75c88-fmzhb trial0009 1 keda
globeco-order-service-6997c75c88-rlffl trial0009 1 keda
globeco-portfolio-service-hpa trial0009 3 keda
globeco-portfolio-service-hpa trial0009 1 keda
globeco-pricing-service-64498f4df5-475xm trial0009 1 keda
globeco-confirmation-service-74dd5df469-6vvtl trial0013 1 keda
globeco-confirmation-service-74dd5df469-dfnbt trial0013 1 keda
globeco-confirmation-service-74dd5df469-dwz8c trial0013 1 keda
globeco-confirmation-service-74dd5df469-k8rn4 trial0013 1 keda
globeco-confirmation-service-74dd5df469-pxcdt trial0013 1 keda
globeco-confirmation-service-74dd5df469-vl9hp trial0013 1 keda
globeco-confirmation-service-74dd5df469-vl9hp trial0013 1 keda
globeco-confirmation-service-74dd5df469-vqdp5 trial0013 1 keda
globeco-confirmation-service-74dd5df469-wt47h trial0013 1 keda
globeco-execution-service-6df778fb86-hvtrq trial0013 3 keda
globeco-execution-service-hpa trial0013 1 keda
globeco-fix-engine-d95677f59-2jvkg trial0013 1 keda
globeco-fix-engine-d95677f59-2l2tc trial0013 1 keda
globeco-fix-engine-d95677f59-2l2tc trial0013 1 keda
globeco-fix-engine-d95677f59-2nrvd trial0013 1 keda
globeco-fix-engine-d95677f59-2nrvd trial0013 1 keda
globeco-fix-engine-d95677f59-4c8pm trial0013 1 keda
globeco-fix-engine-d95677f59-4c8pm trial0013 1 keda
globeco-fix-engine-d95677f59-4kdlq trial0013 1 keda
globeco-fix-engine-d95677f59-4kdlq trial0013 1 keda
globeco-fix-engine-d95677f59-4rhk8 trial0013 1 keda
globeco-fix-engine-d95677f59-4rhk8 trial0013 1 keda
globeco-fix-engine-d95677f59-4t62t trial0013 1 keda
globeco-fix-engine-d95677f59-5csxq trial0013 1 keda
globeco-fix-engine-d95677f59-5khl6 trial0013 1 keda
globeco-fix-engine-d95677f59-5khl6 trial0013 1 keda

In [172]:
df = pd.DataFrame(results)
# display all the rows of the dataframe
with pd.option_context('display.max_rows', None):
    display(df[df.trial_id == "trial0004"])

,action,type,reason,count,first_timestamp,last_timestamp,trial_start_time,trial_end_time,duration,kind,name,namespace,message,trial_id,autoscaler
25,None,Warning,FailedPreStopHook,1,2026-09-18 23:41:30+00:00,2026-09-18 23:41:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-27rg6,globeco,PreStopHook failed,trial0004,keda
26,None,Warning,FailedPreStopHook,1,2026-09-18 23:39:45+00:00,2026-09-18 23:39:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-69qpx,globeco,PreStopHook failed,trial0004,keda
27,None,Warning,FailedPreStopHook,1,2026-09-18 23:32:45+00:00,2026-09-18 23:32:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-8rhmf,globeco,PreStopHook failed,trial0004,keda
28,None,Warning,FailedPreStopHook,1,2026-09-18 23:38:00+00:00,2026-09-18 23:38:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-9xcsr,globeco,PreStopHook failed,trial0004,keda
29,None,Warning,FailedPreStopHook,1,2026-09-18 23:32:45+00:00,2026-09-18 23:32:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-h7f6v,globeco,PreStopHook failed,trial0004,keda
30,None,Warning,FailedPreStopHook,1,2026-09-18 23:48:31+00:00,2026-09-18 23:48:31+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-j5blb,globeco,PreStopHook failed,trial0004,keda
31,None,Warning,Unhealthy,1,2026-09-18 23:48:31+00:00,2026-09-18 23:48:31+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-j5blb,globeco,"Readiness probe failed: Get ""http://10.244.2.6...",trial0004,keda
32,None,Warning,FailedPreStopHook,1,2026-09-18 23:32:45+00:00,2026-09-18 23:32:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-lkxfp,globeco,PreStopHook failed,trial0004,keda
33,None,Warning,FailedPreStopHook,1,2026-09-18 23:38:00+00:00,2026-09-18 23:38:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-lqr2x,globeco,PreStopHook failed,trial0004,keda
34,None,Warning,FailedPreStopHook,1,2026-09-18 23:30:15+00:00,2026-09-18 23:30:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-qzzsv,globeco,PreStopHook failed,trial0004,keda
35,None,Warning,Unhealthy,1,2026-09-18 23:30:15+00:00,2026-09-18 23:30:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-qzzsv,globeco,Readiness probe failed: HTTP probe failed with...,trial0004,keda
36,None,Warning,FailedPreStopHook,1,2026-09-18 23:48:16+00:00,2026-09-18 23:48:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-xc8bp,globeco,PreStopHook failed,trial0004,keda
37,None,Warning,FailedPreStopHook,1,2026-09-18 23:29:15+00:00,2026-09-18 23:29:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-xf6wn,globeco,PreStopHook failed,trial0004,keda
38,None,Warning,FailedPreStopHook,1,2026-09-18 23:34:15+00:00,2026-09-18 23:34:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-confirmation-service-74dd5df469-z45t4,globeco,PreStopHook failed,trial0004,keda
39,None,Warning,Unhealthy,2,2026-09-18 23:36:27+00:00,2026-09-18 23:36:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:03,Pod,globeco-execution-service-6df778fb86-smsdl,globeco,"Startup probe failed: Get ""http://10.244.1.74:...",trial0004,keda
40,None,Warning,Unhealthy,1,2026-09-18 23:28:00+00:00,2026-09-18 23:28:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-2fhk2,globeco,"Readiness probe failed: Get ""http://10.244.1.3...",trial0004,keda
41,None,Warning,Unhealthy,1,2026-09-18 23:29:45+00:00,2026-09-18 23:29:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-2mqfk,globeco,"Readiness probe failed: Get ""http://10.244.1.4...",trial0004,keda
42,None,Warning,Unhealthy,1,2026-09-18 23:51:46+00:00,2026-09-18 23:51:46+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-2wxgw,globeco,"Startup probe failed: Get ""http://10.244.2.104...",trial0004,keda
43,None,Warning,Unhealthy,1,2026-09-18 23:52:46+00:00,2026-09-18 23:52:46+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-2wxgw,globeco,"Readiness probe failed: Get ""http://10.244.2.1...",trial0004,keda
44,None,Warning,Unhealthy,1,2026-09-18 23:27:05+00:00,2026-09-18 23:27:05+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-2zgxd,globeco,"Startup probe failed: Get ""http://10.244.2.31:...",trial0004,keda
45,None,Warning,Unhealthy,1,2026-09-18 23:28:00+00:00,2026-09-18 23:28:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-2zgxd,globeco,"Readiness probe failed: Get ""http://10.244.2.3...",trial0004,keda
46,None,Warning,Unhealthy,1,2026-09-18 23:35:00+00:00,2026-09-18 23:35:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-42mjq,globeco,"Readiness probe failed: Get ""http://10.244.1.6...",trial0004,keda
47,None,Warning,Unhealthy,1,2026-09-18 23:51:01+00:00,2026-09-18 23:51:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-49bzm,globeco,"Readiness probe failed: Get ""http://10.244.2.9...",trial0004,keda
48,None,Warning,Unhealthy,1,2026-09-18 23:54:31+00:00,2026-09-18 23:54:31+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-4cwsl,globeco,"Readiness probe failed: Get ""http://10.244.2.1...",trial0004,keda
49,None,Warning,Unhealthy,1,2026-09-18 23:44:16+00:00,2026-09-18 23:44:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-4gqm8,globeco,"Readiness probe failed: Get ""http://10.244.2.7...",trial0004,keda
50,None,Warning,Unhealthy,1,2026-09-18 23:28:45+00:00,2026-09-18 23:28:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-4rhv2,globeco,"Startup probe failed: Get ""http://10.244.2.43:...",trial0004,keda
51,None,Warning,Unhealthy,1,2026-09-18 23:29:45+00:00,2026-09-18 23:29:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-4rhv2,globeco,"Readiness probe failed: Get ""http://10.244.2.4...",trial0004,keda
52,None,Warning,Unhealthy,1,2026-09-18 23:35:00+00:00,2026-09-18 23:35:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-4xnk9,globeco,"Readiness probe failed: Get ""http://10.244.1.6...",trial0004,keda
53,None,Warning,Unhealthy,1,2026-09-18 23:41:01+00:00,2026-09-18 23:41:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-579dc,globeco,"Startup probe failed: Get ""http://10.244.1.87:...",trial0004,keda
54,None,Warning,Unhealthy,1,2026-09-18 23:42:16+00:00,2026-09-18 23:42:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-579dc,globeco,"Readiness probe failed: Get ""http://10.244.1.8...",trial0004,keda
55,None,Warning,Unhealthy,1,2026-09-18 23:35:00+00:00,2026-09-18 23:35:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-57wc7,globeco,"Readiness probe failed: Get ""http://10.244.2.5...",trial0004,keda
56,None,Warning,Unhealthy,1,2026-09-18 23:31:30+00:00,2026-09-18 23:31:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-5qm7k,globeco,"Readiness probe failed: Get ""http://10.244.2.4...",trial0004,keda
57,None,Warning,Unhealthy,1,2026-09-18 23:43:01+00:00,2026-09-18 23:43:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-5qzxx,globeco,"Startup probe failed: Get ""http://10.244.2.78:...",trial0004,keda
58,None,Warning,Unhealthy,1,2026-09-18 23:44:01+00:00,2026-09-18 23:44:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-5qzxx,globeco,"Readiness probe failed: Get ""http://10.244.2.7...",trial0004,keda
59,None,Warning,Unhealthy,1,2026-09-18 23:54:31+00:00,2026-09-18 23:54:31+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-67fdv,globeco,"Readiness probe failed: Get ""http://10.244.1.1...",trial0004,keda
60,None,Warning,Unhealthy,1,2026-09-18 23:39:00+00:00,2026-09-18 23:39:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-6b2l6,globeco,"Startup probe failed: Get ""http://10.244.1.81:...",trial0004,keda
61,None,Warning,Unhealthy,1,2026-09-18 23:40:30+00:00,2026-09-18 23:40:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-6b2l6,globeco,"Readiness probe failed: Get ""http://10.244.1.8...",trial0004,keda
62,None,Warning,Unhealthy,1,2026-09-18 23:36:45+00:00,2026-09-18 23:36:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-6t94b,globeco,"Readiness probe failed: Get ""http://10.244.2.6...",trial0004,keda
63,None,Warning,Unhealthy,1,2026-09-18 23:33:45+00:00,2026-09-18 23:33:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-6v264,globeco,"Startup probe failed: Get ""http://10.244.2.53:...",trial0004,keda
64,None,Warning,Unhealthy,1,2026-09-18 23:35:00+00:00,2026-09-18 23:35:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-6v264,globeco,"Readiness probe failed: Get ""http://10.244.2.5...",trial0004,keda
65,None,Warning,Unhealthy,1,2026-09-18 23:33:15+00:00,2026-09-18 23:33:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-6vv56,globeco,"Readiness probe failed: Get ""http://10.244.1.5...",trial0004,keda
66,None,Warning,Unhealthy,1,2026-09-18 23:28:00+00:00,2026-09-18 23:28:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-77zn7,globeco,"Readiness probe failed: Get ""http://10.244.1.3...",trial0004,keda
67,None,Warning,Unhealthy,1,2026-09-18 23:26:45+00:00,2026-09-18 23:26:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-7hh6m,globeco,"Startup probe failed: Get ""http://10.244.1.32:...",trial0004,keda
68,None,Warning,Unhealthy,1,2026-09-18 23:28:00+00:00,2026-09-18 23:28:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-7hh6m,globeco,"Readiness probe failed: Get ""http://10.244.1.3...",trial0004,keda
69,None,Warning,Unhealthy,1,2026-09-18 23:45:01+00:00,2026-09-18 23:45:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-7nlbr,globeco,"Startup probe failed: Get ""http://10.244.2.82:...",trial0004,keda
70,None,Warning,Unhealthy,1,2026-09-18 23:46:06+00:00,2026-09-18 23:46:06+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-7nlbr,globeco,"Readiness probe failed: Get ""http://10.244.2.8...",trial0004,keda
71,None,Warning,Unhealthy,1,2026-09-18 23:43:01+00:00,2026-09-18 23:43:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-7pbrw,globeco,"Startup probe failed: Get ""http://10.244.1.93:...",trial0004,keda
72,None,Warning,Unhealthy,1,2026-09-18 23:44:01+00:00,2026-09-18 23:44:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-7pbrw,globeco,"Readiness probe failed: Get ""http://10.244.1.9...",trial0004,keda
73,None,Warning,Unhealthy,1,2026-09-18 23:31:30+00:00,2026-09-18 23:31:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-8wnnx,globeco,"Readiness probe failed: Get ""http://10.244.1.5...",trial0004,keda
74,None,Warning,Unhealthy,1,2026-09-18 23:26:45+00:00,2026-09-18 23:26:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-95lvg,globeco,"Startup probe failed: Get ""http://10.244.2.28:...",trial0004,keda
75,None,Warning,Unhealthy,1,2026-09-18 23:28:00+00:00,2026-09-18 23:28:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-95lvg,globeco,"Readiness probe failed: Get ""http://10.244.2.2...",trial0004,keda
76,None,Warning,Unhealthy,1,2026-09-18 23:53:16+00:00,2026-09-18 23:53:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9ctsd,globeco,"Startup probe failed: Get ""http://10.244.1.107...",trial0004,keda
77,None,Warning,Unhealthy,1,2026-09-18 23:30:15+00:00,2026-09-18 23:30:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9pr6n,globeco,"Startup probe failed: Get ""http://10.244.1.51:...",trial0004,keda
78,None,Warning,Unhealthy,1,2026-09-18 23:31:30+00:00,2026-09-18 23:31:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9pr6n,globeco,"Readiness probe failed: Get ""http://10.244.1.5...",trial0004,keda
79,None,Warning,Unhealthy,1,2026-09-18 23:35:00+00:00,2026-09-18 23:35:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9qctv,globeco,"Readiness probe failed: Get ""http://10.244.2.5...",trial0004,keda
80,None,Warning,Unhealthy,1,2026-09-18 23:26:45+00:00,2026-09-18 23:26:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9t8jh,globeco,"Startup probe failed: Get ""http://10.244.2.27:...",trial0004,keda
81,None,Warning,Unhealthy,1,2026-09-18 23:28:00+00:00,2026-09-18 23:28:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9t8jh,globeco,"Readiness probe failed: Get ""http://10.244.2.2...",trial0004,keda
82,None,Warning,Unhealthy,1,2026-09-18 23:41:01+00:00,2026-09-18 23:41:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9vqvx,globeco,"Startup probe failed: Get ""http://10.244.1.86:...",trial0004,keda
83,None,Warning,Unhealthy,1,2026-09-18 23:42:16+00:00,2026-09-18 23:42:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-9vqvx,globeco,"Readiness probe failed: Get ""http://10.244.1.8...",trial0004,keda
84,None,Warning,Unhealthy,1,2026-09-18 23:49:16+00:00,2026-09-18 23:49:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-b4cbm,globeco,"Readiness probe failed: Get ""http://10.244.2.9...",trial0004,keda
85,None,Warning,Unhealthy,1,2026-09-18 23:46:01+00:00,2026-09-18 23:46:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-b4f5s,globeco,"Readiness probe failed: Get ""http://10.244.2.8...",trial0004,keda
86,None,Warning,Unhealthy,1,2026-09-18 23:29:45+00:00,2026-09-18 23:29:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-b4tgv,globeco,"Readiness probe failed: Get ""http://10.244.1.4...",trial0004,keda
87,None,Warning,Unhealthy,1,2026-09-18 23:36:45+00:00,2026-09-18 23:36:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-bsz5z,globeco,"Readiness probe failed: Get ""http://10.244.1.7...",trial0004,keda
88,None,Warning,Unhealthy,1,2026-09-18 23:52:46+00:00,2026-09-18 23:52:46+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-bwdv5,globeco,"Readiness probe failed: Get ""http://10.244.1.1...",trial0004,keda
89,None,Warning,Unhealthy,1,2026-09-18 23:30:15+00:00,2026-09-18 23:30:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-ch75k,globeco,"Startup probe failed: Get ""http://10.244.2.45:...",trial0004,keda
90,None,Warning,Unhealthy,1,2026-09-18 23:31:30+00:00,2026-09-18 23:31:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-ch75k,globeco,"Readiness probe failed: Get ""http://10.244.2.4...",trial0004,keda
91,None,Warning,Unhealthy,1,2026-09-18 23:45:01+00:00,2026-09-18 23:45:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-crhpj,globeco,"Startup probe failed: Get ""http://10.244.2.84:...",trial0004,keda
92,None,Warning,Unhealthy,1,2026-09-18 23:46:01+00:00,2026-09-18 23:46:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-crhpj,globeco,"Readiness probe failed: Get ""http://10.244.2.8...",trial0004,keda
93,None,Warning,Unhealthy,1,2026-09-18 23:47:31+00:00,2026-09-18 23:47:31+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-cvgzn,globeco,"Readiness probe failed: Get ""http://10.244.2.8...",trial0004,keda
94,None,Warning,Unhealthy,1,2026-09-18 23:28:45+00:00,2026-09-18 23:28:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-dwmtd,globeco,"Startup probe failed: Get ""http://10.244.1.48:...",trial0004,keda
95,None,Warning,Unhealthy,1,2026-09-18 23:29:45+00:00,2026-09-18 23:29:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-dwmtd,globeco,"Readiness probe failed: Get ""http://10.244.1.4...",trial0004,keda
96,None,Warning,Unhealthy,1,2026-09-18 23:51:01+00:00,2026-09-18 23:51:01+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days 00:00:00,Pod,globeco-fix-engine-d95677f59-dzwqz,globeco,"Readiness probe failed: Get ""http://10.244.2.9...",trial0004,keda

In [173]:
with pd.option_context('display.max_rows', None):
    display(df[df.reason == "FailedPreStopHook"])

,action,type,reason,count,first_timestamp,last_timestamp,trial_start_time,trial_end_time,duration,kind,name,namespace,message,trial_id,autoscaler
25,None,Warning,FailedPreStopHook,1,2026-09-18 23:41:30+00:00,2026-09-18 23:41:30+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-27rg6,globeco,PreStopHook failed,trial0004,keda
26,None,Warning,FailedPreStopHook,1,2026-09-18 23:39:45+00:00,2026-09-18 23:39:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-69qpx,globeco,PreStopHook failed,trial0004,keda
27,None,Warning,FailedPreStopHook,1,2026-09-18 23:32:45+00:00,2026-09-18 23:32:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-8rhmf,globeco,PreStopHook failed,trial0004,keda
28,None,Warning,FailedPreStopHook,1,2026-09-18 23:38:00+00:00,2026-09-18 23:38:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-9xcsr,globeco,PreStopHook failed,trial0004,keda
29,None,Warning,FailedPreStopHook,1,2026-09-18 23:32:45+00:00,2026-09-18 23:32:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-h7f6v,globeco,PreStopHook failed,trial0004,keda
30,None,Warning,FailedPreStopHook,1,2026-09-18 23:48:31+00:00,2026-09-18 23:48:31+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-j5blb,globeco,PreStopHook failed,trial0004,keda
32,None,Warning,FailedPreStopHook,1,2026-09-18 23:32:45+00:00,2026-09-18 23:32:45+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-lkxfp,globeco,PreStopHook failed,trial0004,keda
33,None,Warning,FailedPreStopHook,1,2026-09-18 23:38:00+00:00,2026-09-18 23:38:00+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-lqr2x,globeco,PreStopHook failed,trial0004,keda
34,None,Warning,FailedPreStopHook,1,2026-09-18 23:30:15+00:00,2026-09-18 23:30:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-qzzsv,globeco,PreStopHook failed,trial0004,keda
36,None,Warning,FailedPreStopHook,1,2026-09-18 23:48:16+00:00,2026-09-18 23:48:16+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-xc8bp,globeco,PreStopHook failed,trial0004,keda
37,None,Warning,FailedPreStopHook,1,2026-09-18 23:29:15+00:00,2026-09-18 23:29:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-xf6wn,globeco,PreStopHook failed,trial0004,keda
38,None,Warning,FailedPreStopHook,1,2026-09-18 23:34:15+00:00,2026-09-18 23:34:15+00:00,2026-09-18 23:24:46.327266+00:00,2026-09-18 23:54:50.591000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-z45t4,globeco,PreStopHook failed,trial0004,keda
236,None,Warning,FailedPreStopHook,1,2026-09-19 04:10:43+00:00,2026-09-19 04:10:43+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-fw88h,globeco,PreStopHook failed,trial0009,keda
237,None,Warning,FailedPreStopHook,1,2026-09-19 03:47:27+00:00,2026-09-19 03:47:27+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-g6242,globeco,PreStopHook failed,trial0009,keda
238,None,Warning,FailedPreStopHook,1,2026-09-19 04:10:43+00:00,2026-09-19 04:10:43+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-gdndk,globeco,PreStopHook failed,trial0009,keda
239,None,Warning,FailedPreStopHook,1,2026-09-19 03:44:57+00:00,2026-09-19 03:44:57+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-gjf9g,globeco,PreStopHook failed,trial0009,keda
240,None,Warning,FailedPreStopHook,1,2026-09-19 03:48:57+00:00,2026-09-19 03:48:57+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-kmvfm,globeco,PreStopHook failed,trial0009,keda
241,None,Warning,FailedPreStopHook,1,2026-09-19 04:01:28+00:00,2026-09-19 04:01:28+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-mr52t,globeco,PreStopHook failed,trial0009,keda
242,None,Warning,FailedPreStopHook,1,2026-09-19 03:56:57+00:00,2026-09-19 03:56:57+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-vd4tt,globeco,PreStopHook failed,trial0009,keda
243,None,Warning,FailedPreStopHook,1,2026-09-19 03:55:42+00:00,2026-09-19 03:55:42+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-vwbjs,globeco,PreStopHook failed,trial0009,keda
244,None,Warning,FailedPreStopHook,1,2026-09-19 04:03:13+00:00,2026-09-19 04:03:13+00:00,2026-09-19 03:40:39.006191+00:00,2026-09-19 04:10:43.485000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-w877z,globeco,PreStopHook failed,trial0009,keda
398,None,Warning,FailedPreStopHook,1,2026-09-19 04:33:33+00:00,2026-09-19 04:33:33+00:00,2026-09-19 04:33:27.784625+00:00,2026-09-19 05:03:32.563000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-9b5fm,globeco,PreStopHook failed,trial0010,vpa
413,None,Warning,FailedPreStopHook,1,2026-09-19 05:25:29+00:00,2026-09-19 05:25:29+00:00,2026-09-19 05:25:22.265083+00:00,2026-09-19 05:55:28.615000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-9sbx8,globeco,PreStopHook failed,trial0011,vpa
431,None,Warning,FailedPreStopHook,1,2026-09-19 07:28:09+00:00,2026-09-19 07:28:09+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-6vvtl,globeco,PreStopHook failed,trial0013,keda
432,None,Warning,FailedPreStopHook,1,2026-09-19 07:14:08+00:00,2026-09-19 07:14:08+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-dfnbt,globeco,PreStopHook failed,trial0013,keda
433,None,Warning,FailedPreStopHook,1,2026-09-19 07:26:24+00:00,2026-09-19 07:26:24+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-dwz8c,globeco,PreStopHook failed,trial0013,keda
434,None,Warning,FailedPreStopHook,1,2026-09-19 07:32:39+00:00,2026-09-19 07:32:39+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-k8rn4,globeco,PreStopHook failed,trial0013,keda
435,None,Warning,FailedPreStopHook,1,2026-09-19 07:15:08+00:00,2026-09-19 07:15:08+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-pxcdt,globeco,PreStopHook failed,trial0013,keda
436,None,Warning,FailedPreStopHook,1,2026-09-19 07:22:08+00:00,2026-09-19 07:22:08+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-vl9hp,globeco,PreStopHook failed,trial0013,keda
438,None,Warning,FailedPreStopHook,1,2026-09-19 07:26:24+00:00,2026-09-19 07:26:24+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-vqdp5,globeco,PreStopHook failed,trial0013,keda
439,None,Warning,FailedPreStopHook,1,2026-09-19 07:31:39+00:00,2026-09-19 07:31:39+00:00,2026-09-19 07:07:19.789721+00:00,2026-09-19 07:37:25.271000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-wt47h,globeco,PreStopHook failed,trial0013,keda
635,None,Warning,FailedPreStopHook,1,2026-09-19 08:57:58+00:00,2026-09-19 08:57:58+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-4ntdr,globeco,PreStopHook failed,trial0015,keda
637,None,Warning,FailedPreStopHook,1,2026-09-19 09:05:58+00:00,2026-09-19 09:05:58+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-4v658,globeco,PreStopHook failed,trial0015,keda
639,None,Warning,FailedPreStopHook,1,2026-09-19 09:10:14+00:00,2026-09-19 09:10:14+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-69x7g,globeco,PreStopHook failed,trial0015,keda
640,None,Warning,FailedPreStopHook,1,2026-09-19 09:11:44+00:00,2026-09-19 09:11:44+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-8chfg,globeco,PreStopHook failed,trial0015,keda
641,None,Warning,FailedPreStopHook,1,2026-09-19 09:02:58+00:00,2026-09-19 09:02:58+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-8dd9q,globeco,PreStopHook failed,trial0015,keda
643,None,Warning,FailedPreStopHook,1,2026-09-19 08:57:58+00:00,2026-09-19 08:57:58+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-df5m5,globeco,PreStopHook failed,trial0015,keda
644,None,Warning,FailedPreStopHook,1,2026-09-19 09:11:44+00:00,2026-09-19 09:11:44+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-f22hb,globeco,PreStopHook failed,trial0015,keda
645,None,Warning,FailedPreStopHook,1,2026-09-19 08:57:58+00:00,2026-09-19 08:57:58+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-mcdtw,globeco,PreStopHook failed,trial0015,keda
647,None,Warning,FailedPreStopHook,1,2026-09-19 09:10:14+00:00,2026-09-19 09:10:14+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-npkzz,globeco,PreStopHook failed,trial0015,keda
648,None,Warning,FailedPreStopHook,1,2026-09-19 09:11:59+00:00,2026-09-19 09:11:59+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-q2snh,globeco,PreStopHook failed,trial0015,keda
649,None,Warning,FailedPreStopHook,1,2026-09-19 09:10:14+00:00,2026-09-19 09:10:14+00:00,2026-09-19 08:49:44.604894+00:00,2026-09-19 09:19:49.549000+00:00,0 days,Pod,globeco-confirmation-service-74dd5df469-s22g6,globeco,PreStopHook failed,trial0015,keda